#############################################
# Autogenerated at 2018-07-18 14:59:39 +02:00
#############################################

enum Fonts
  CALIBRI               = 0
  KENNEY_BLOCKS         = 1
  KENNEY_FUTURE         = 2
  KENNEY_FUTURE_NARROW  = 3
  KENNEY_HIGH           = 4
  KENNEY_HIGH_SQUARE    = 5
  KENNEY_MINI           = 6
  KENNEY_MINI_SQUARE    = 7
  KENNEY_PIXEL          = 8
  KENNEY_PIXEL_SQUARE   = 9
  KENNEY_ROCKET         = 10
  KENNEY_ROCKET_SQUARE  = 11
end