#############################################
# Autogenerated at 2018-07-18 17:51:12 +02:00
#############################################

enum Music
  JUHANI_JUNKALA_RETRO_GAME_MUSIC_PACK_ENDING        = 0
  JUHANI_JUNKALA_RETRO_GAME_MUSIC_PACK_LEVEL_1       = 1
  JUHANI_JUNKALA_RETRO_GAME_MUSIC_PACK_LEVEL_2       = 2
  JUHANI_JUNKALA_RETRO_GAME_MUSIC_PACK_LEVEL_3       = 3
  JUHANI_JUNKALA_RETRO_GAME_MUSIC_PACK_TITLE_SCREEN  = 4
end