#############################################
# Autogenerated at 2018-10-11 16:07:23 +02:00
#############################################

enum Music
  ENDING        = 0
  LEVEL_1       = 1
  LEVEL_2       = 2
  LEVEL_3       = 3
  TITLE_SCREEN  = 4
end