#############################################
# Autogenerated at 2018-07-19 12:43:45 +02:00
#############################################

enum Sounds
  HIGH_DOWN            = 0
  HIGH_UP              = 1
  LASER1               = 2
  LASER2               = 3
  LASER3               = 4
  LASER4               = 5
  LASER5               = 6
  LASER6               = 7
  LASER7               = 8
  LASER8               = 9
  LASER9               = 10
  LOW_DOWN             = 11
  LOW_RANDOM           = 12
  LOW_THREE_TONE       = 13
  PEP_SOUND1           = 14
  PEP_SOUND2           = 15
  PEP_SOUND3           = 16
  PEP_SOUND4           = 17
  PEP_SOUND5           = 18
  PHASER_DOWN1         = 19
  PHASER_DOWN2         = 20
  PHASER_DOWN3         = 21
  PHASER_UP1           = 22
  PHASER_UP2           = 23
  PHASER_UP3           = 24
  PHASER_UP4           = 25
  PHASER_UP5           = 26
  PHASER_UP6           = 27
  PHASER_UP7           = 28
  PHASE_JUMP1          = 29
  PHASE_JUMP2          = 30
  PHASE_JUMP3          = 31
  PHASE_JUMP4          = 32
  PHASE_JUMP5          = 33
  POWER_UP1            = 34
  POWER_UP10           = 35
  POWER_UP11           = 36
  POWER_UP12           = 37
  POWER_UP2            = 38
  POWER_UP3            = 39
  POWER_UP4            = 40
  POWER_UP5            = 41
  POWER_UP6            = 42
  POWER_UP7            = 43
  POWER_UP8            = 44
  POWER_UP9            = 45
  SPACE_TRASH1         = 46
  SPACE_TRASH2         = 47
  SPACE_TRASH3         = 48
  SPACE_TRASH4         = 49
  SPACE_TRASH5         = 50
  THREE_TONE1          = 51
  THREE_TONE2          = 52
  TONE1                = 53
  TWO_TONE1            = 54
  TWO_TONE2            = 55
  ZAP1                 = 56
  ZAP2                 = 57
  ZAP_THREE_TONE_DOWN  = 58
  ZAP_THREE_TONE_UP    = 59
  ZAP_TWO_TONE         = 60
  ZAP_TWO_TONE2        = 61
end