#############################################
# Autogenerated at 2018-10-12 01:57:18 +02:00
#############################################

module Resource
  enum Sound
    HIGH_DOWN             = 0
    HIGH_UP               = 1
    LASER1                = 2
    LASER2                = 3
    LASER3                = 4
    LASER4                = 5
    LASER5                = 6
    LASER6                = 7
    LASER7                = 8
    LASER8                = 9
    LASER9                = 10
    LOW_DOWN              = 11
    LOW_RANDOM            = 12
    LOW_THREE_TONE        = 13
    ONE                   = 14
    PEP_SOUND1            = 15
    PEP_SOUND2            = 16
    PEP_SOUND3            = 17
    PEP_SOUND4            = 18
    PEP_SOUND5            = 19
    PHASER_DOWN1          = 20
    PHASER_DOWN2          = 21
    PHASER_DOWN3          = 22
    PHASER_UP1            = 23
    PHASER_UP2            = 24
    PHASER_UP3            = 25
    PHASER_UP4            = 26
    PHASER_UP5            = 27
    PHASER_UP6            = 28
    PHASER_UP7            = 29
    PHASE_JUMP1           = 30
    PHASE_JUMP2           = 31
    PHASE_JUMP3           = 32
    PHASE_JUMP4           = 33
    PHASE_JUMP5           = 34
    POWER_UP1             = 35
    POWER_UP10            = 36
    POWER_UP11            = 37
    POWER_UP12            = 38
    POWER_UP2             = 39
    POWER_UP3             = 40
    POWER_UP4             = 41
    POWER_UP5             = 42
    POWER_UP6             = 43
    POWER_UP7             = 44
    POWER_UP8             = 45
    POWER_UP9             = 46
    SPACE_TRASH1          = 47
    SPACE_TRASH2          = 48
    SPACE_TRASH3          = 49
    SPACE_TRASH4          = 50
    SPACE_TRASH5          = 51
    SURVIVE               = 52
    THREE                 = 53
    THREE_TONE1           = 54
    THREE_TONE2           = 55
    TONE1                 = 56
    TWO                   = 57
    TWO_TONE1             = 58
    TWO_TONE2             = 59
    WARNING50HP           = 60
    WARNING_METEOR_STORM  = 61
    ZAP1                  = 62
    ZAP2                  = 63
    ZAP_THREE_TONE_DOWN   = 64
    ZAP_THREE_TONE_UP     = 65
    ZAP_TWO_TONE          = 66
    ZAP_TWO_TONE2         = 67
  end
end