#############################################
# Autogenerated at 2018-07-18 14:59:39 +02:00
#############################################

enum Textures
  BACKGROUND         = 0
  BLUE_PANEL         = 1
  CURSOR             = 2
  ENEMY_CARRIER      = 3
  ENEMY_FIGHTER      = 4
  ENEMY_INTERCEPTOR  = 5
  LASER_GREEN        = 6
  LASER_RED          = 7
  METEOR_BIG1        = 8
  METEOR_BIG2        = 9
  METEOR_BIG3        = 10
  METEOR_BIG4        = 11
  METEOR_MED1        = 12
  METEOR_MED2        = 13
  METEOR_SMALL1      = 14
  METEOR_SMALL2      = 15
  METEOR_TINY1       = 16
  METEOR_TINY2       = 17
  PICKUP_HEALTH      = 18
  PICKUP_KNOCK       = 19
  PLAYER             = 20
end