#############################################
# Autogenerated at 2018-10-12 01:57:18 +02:00
#############################################

enum Textures
  BACKGROUND         = 0
  CURSOR             = 1
  ENEMY_CARRIER      = 2
  ENEMY_FIGHTER      = 3
  ENEMY_INTERCEPTOR  = 4
  LASER_GREEN        = 5
  LASER_RED          = 6
  METEOR_BIG1        = 7
  METEOR_BIG2        = 8
  METEOR_BIG3        = 9
  METEOR_BIG4        = 10
  METEOR_MED1        = 11
  METEOR_MED2        = 12
  METEOR_SMALL1      = 13
  METEOR_SMALL2      = 14
  METEOR_TINY1       = 15
  METEOR_TINY2       = 16
  PICKUP_HEALTH      = 17
  PICKUP_KNOCK       = 18
  PLAYER             = 19
end