#############################################
# Autogenerated at 2018-07-14 17:04:34 +02:00
#############################################

enum Textures
  Background        = 0
  Cursor            = 1
  EnemyCarrier      = 2
  EnemyFighter      = 3
  EnemyInterceptor  = 4
  LaserGreen        = 5
  LaserRed          = 6
  MeteorBig1        = 7
  MeteorBig2        = 8
  MeteorBig3        = 9
  MeteorBig4        = 10
  MeteorMed1        = 11
  MeteorMed2        = 12
  MeteorSmall1      = 13
  MeteorSmall2      = 14
  MeteorTiny1       = 15
  MeteorTiny2       = 16
  PickupHealth      = 17
  PickupKnock       = 18
  Player            = 19
end